// Generated by CoffeeScript 1.10.0
(function() {
  var PresentationFramework, _, fm, fs, handlebars, loadCollection, log, log_colours, logger, mkdirp, path, pickSlides, saveDeck, slidewinder, yaml;

  fs = require('fs');

  path = require('path');

  fm = require('front-matter');

  handlebars = require('handlebars');

  _ = require('lodash');

  mkdirp = require('mkdirp');

  yaml = require('js-yaml');

  logger = require('./log.js');

  log_colours = {
    silly: 'magenta',
    input: 'grey',
    verbose: 'cyan',
    prompt: 'grey',
    debug: 'blue',
    info: 'green',
    data: 'grey',
    help: 'cyan',
    warn: 'yellow',
    error: 'red'
  };

  loadCollection = function(dirpath) {
    var collection, slidenum;
    collection = {};
    fs.readdirSync(dirpath).forEach(function(file) {
      var data, filepath, name, slide;
      filepath = path.resolve(dirpath, file);
      data = fs.readFileSync(filepath, 'utf8');
      slide = fm(data);
      name = slide.attributes.name;
      if (collection[name]) {
        return log.error('Multiple slides have the name', name);
      } else {
        return collection[name] = slide;
      }
    });
    slidenum = Object.keys(collection).length;
    log.info('Loaded', slidenum, 'markdown slide files from', dirpath);
    return collection;
  };

  pickSlides = function(collection, selections) {
    var picked;
    picked = [];
    selections.forEach(function(selection) {
      var slide;
      slide = collection[selection];
      if (slide) {
        return picked.push(slide);
      } else {
        return log.error('No slide found with name', name);
      }
    });
    log.info('Picked', picked.length, 'slides from collection');
    return picked;
  };

  PresentationFramework = (function() {
    function PresentationFramework(framework) {
      var frameworkPath;
      log.info('Looking for presentation framework module: ', framework);
      frameworkPath = path.join(framework, 'template.html');
      this.template = fs.readFileSync(frameworkPath, 'utf8');
      this.renderer = handlebars.compile(this.template);
      this.helpers = require(path.join(framework, 'helpers.js'));
      this.renderDeck = (function(_this) {
        return function(renderContext) {
          var deck;
          Object.keys(_this.helpers).forEach(function(key) {
            return handlebars.registerHelper(key, _this.helpers[key]);
          });
          deck = _this.renderer(renderContext);
          return deck;
        };
      })(this);
      this;
    }

    return PresentationFramework;

  })();

  saveDeck = function(deck, data) {
    var dataOutput, dataPath, deckPath, msg;
    mkdirp(data.output);
    deckPath = path.resolve(data.output, 'index.html');
    fs.writeFileSync(deckPath, deck);
    dataPath = path.resolve(data.output, 'deck.json');
    dataOutput = JSON.stringify(data, null, 2);
    fs.writeFileSync(dataPath, dataOutput);
    msg = 'Deck (index.html) and Data (deck.json) saved to ';
    return log.info(msg, data.output);
  };

  slidewinder = function(sessionData) {
    var allSlides, deck, plugin, renderContext;
    allSlides = loadCollection(sessionData.collection);
    sessionData.slideset = pickSlides(allSlides, sessionData.slides);
    plugin = new PresentationFramework(sessionData.framework);
    renderContext = {
      deck: {
        title: sessionData.title,
        author: sessionData.author
      },
      slides: sessionData.slideset
    };
    deck = plugin.renderDeck(renderContext);
    return saveDeck(deck, sessionData);
  };

  log = logger();

  module.exports = slidewinder;

}).call(this);
